package fr.maxlego08.sarah.dialect;

import fr.maxlego08.sarah.DatabaseConfiguration;
import fr.maxlego08.sarah.DatabaseConnection;
import fr.maxlego08.sarah.conditions.ColumnDefinition;
import fr.maxlego08.sarah.exceptions.DatabaseException;
import fr.maxlego08.sarah.logger.Logger;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public class PostgreSqlDialect extends AbstractSqlDialect {

    public PostgreSqlDialect() {
        super("\"");
    }

    @Override
    public String driverClassName() {
        return "org.postgresql.Driver";
    }

    @Override
    public String jdbcUrl(DatabaseConfiguration configuration) {
        return "jdbc:postgresql://" + configuration.getHost() + ":" + configuration.getPort() + "/" + configuration.getDatabase();
    }

    @Override
    public String autoIncrementKeyword(ColumnDefinition column) {
        return column != null && column.isAutoIncrement() ? "GENERATED BY DEFAULT AS IDENTITY" : "";
    }

    @Override
    public String enumColumnType(ColumnDefinition column) {
        return "TEXT";
    }

    @Override
    public List<ColumnDefinition> missingColumns(DatabaseConnection connection, Logger logger, String tableName, List<ColumnDefinition> expectedColumns) {
        Objects.requireNonNull(connection, "connection");
        Objects.requireNonNull(tableName, "tableName");
        Objects.requireNonNull(expectedColumns, "expectedColumns");

        List<ColumnDefinition> missing = new ArrayList<ColumnDefinition>();

        try (Connection sqlConnection = connection.getConnection()) {
            for (ColumnDefinition column : expectedColumns) {
                String columnName = column.getName();
                long count = countExistingColumn(
                        sqlConnection,
                        "SELECT COUNT(*) FROM information_schema.columns WHERE table_name = ? AND table_schema = ? AND column_name = ?",
                        tableName,
                        "public",
                        columnName
                );
                if (count == 0) {
                    missing.add(column);
                }
            }
        } catch (SQLException exception) {
            if (logger != null) {
                logger.info("Failed to check PostgreSQL table info for '" + tableName + "': " + exception.getMessage());
            }
            throw new DatabaseException("missing-columns", tableName, exception);
        }

        return missing;
    }
}
