package fr.maxlego08.sarah.dialect;

import fr.maxlego08.sarah.DatabaseConfiguration;
import fr.maxlego08.sarah.DatabaseConnection;
import fr.maxlego08.sarah.conditions.ColumnDefinition;
import fr.maxlego08.sarah.exceptions.DatabaseException;
import fr.maxlego08.sarah.logger.Logger;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Objects;

public class PostgreSqlDialect extends AbstractSqlDialect {

    public PostgreSqlDialect() {
        super("\"");
    }

    @Override
    public String driverClassName() {
        return "org.postgresql.Driver";
    }

    @Override
    public String jdbcUrl(DatabaseConfiguration configuration) {
        return "jdbc:postgresql://" + configuration.getHost() + ":" + configuration.getPort() + "/" + configuration.getDatabase();
    }

    @Override
    public String autoIncrementKeyword(ColumnDefinition column) {
        return column != null && column.isAutoIncrement() ? "GENERATED BY DEFAULT AS IDENTITY" : "";
    }

    @Override
    public String enumColumnType(ColumnDefinition column) {
        return "TEXT";
    }

    @Override
    protected String mapColumnType(ColumnDefinition column, String baseType) {
        switch (baseType.toUpperCase(Locale.ROOT)) {
            case "LONGTEXT":
            case "MEDIUMTEXT":
            case "TINYTEXT":
                return "TEXT";
            case "BLOB":
            case "LONGBLOB":
            case "MEDIUMBLOB":
            case "TINYBLOB":
                return "BYTEA";
            default:
                return baseType;
        }
    }

    @Override
    public List<ColumnDefinition> missingColumns(DatabaseConnection connection, Logger logger, String tableName, List<ColumnDefinition> expectedColumns) {
        Objects.requireNonNull(connection, "connection");
        Objects.requireNonNull(tableName, "tableName");
        Objects.requireNonNull(expectedColumns, "expectedColumns");

        List<ColumnDefinition> missing = new ArrayList<ColumnDefinition>();

        try (Connection sqlConnection = connection.getConnection()) {
            TableRef ref = resolveTableRef(sqlConnection, tableName);
            for (ColumnDefinition column : expectedColumns) {
                String columnName = column.getName();
                long count = countExistingColumn(
                        sqlConnection,
                        "SELECT COUNT(*) FROM information_schema.columns WHERE table_name = ? AND table_schema = ? AND column_name = ?",
                        ref.table,
                        ref.schema,
                        columnName
                );
                if (count == 0) {
                    missing.add(column);
                }
            }
        } catch (SQLException exception) {
            if (logger != null) {
                logger.info("Failed to check PostgreSQL table info for '" + tableName + "': " + exception.getMessage());
            }
            throw new DatabaseException("missing-columns", tableName, exception);
        }

        return missing;
    }

    private TableRef resolveTableRef(Connection sqlConnection, String tableReference) throws SQLException {
        String trimmed = tableReference == null ? "" : tableReference.trim();
        if (trimmed.isEmpty()) {
            throw new IllegalArgumentException("tableName cannot be null or empty");
        }

        String base = trimmed;
        int firstWhitespace = -1;
        for (int i = 0; i < trimmed.length(); i++) {
            if (Character.isWhitespace(trimmed.charAt(i))) {
                firstWhitespace = i;
                break;
            }
        }
        if (firstWhitespace != -1) {
            base = trimmed.substring(0, firstWhitespace);
        }

        String schema = null;
        String table = base;
        int dotIndex = base.lastIndexOf('.');
        if (dotIndex != -1) {
            schema = base.substring(0, dotIndex);
            table = base.substring(dotIndex + 1);
        }

        if (schema == null || schema.isEmpty()) {
            schema = safeCurrentSchema(sqlConnection);
        }
        if (schema == null || schema.isEmpty()) {
            schema = "public";
        }

        return new TableRef(schema, table);
    }

    private String safeCurrentSchema(Connection sqlConnection) throws SQLException {
        try {
            String schema = sqlConnection.getSchema();
            if (schema != null && !schema.trim().isEmpty()) {
                return schema.trim();
            }
        } catch (Throwable ignored) {
            // Some drivers may not support getSchema consistently.
        }

        try (PreparedStatement statement = sqlConnection.prepareStatement("SELECT current_schema()")) {
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    String schema = resultSet.getString(1);
                    return schema == null ? null : schema.trim();
                }
            }
        }

        return null;
    }

    private static final class TableRef {
        private final String schema;
        private final String table;

        private TableRef(String schema, String table) {
            this.schema = schema;
            this.table = table;
        }
    }
}
