package fr.maxlego08.sarah;

import fr.maxlego08.sarah.database.DatabaseType;
import fr.maxlego08.sarah.database.Schema;
import fr.maxlego08.sarah.dialect.SqlDialects;
import fr.maxlego08.sarah.conditions.ColumnDefinition;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class DialectTest {

    @Test
    public void testDialectIdentifierQuoting() {
        assertEquals("`user_name`", SqlDialects.from(DatabaseType.MYSQL).quoteIdentifier("user_name"));
        assertEquals("`user_name`", SqlDialects.from(DatabaseType.MARIADB).quoteIdentifier("user_name"));
        assertEquals("`user_name`", SqlDialects.from(DatabaseType.SQLITE).quoteIdentifier("user_name"));
        assertEquals("\"user_name\"", SqlDialects.from(DatabaseType.POSTGRESQL).quoteIdentifier("user_name"));
    }

    @Test
    public void testQualifiedIdentifierQuoting() {
        assertEquals("u.`name`", SqlDialects.from(DatabaseType.MYSQL).qualifyIdentifier("u", "name"));
        assertEquals("u.\"name\"", SqlDialects.from(DatabaseType.POSTGRESQL).qualifyIdentifier("u", "name"));
        assertEquals("\"name\"", SqlDialects.from(DatabaseType.POSTGRESQL).qualifyIdentifier(null, "name"));
    }

    @Test
    public void testNullDatabaseTypeFails() {
        assertThrows(IllegalArgumentException.class, () -> SqlDialects.from(null));
    }

    @Test
    public void testCreateTableSuffixes() {
        assertEquals(" ENGINE=InnoDB DEFAULT CHARSET=utf8mb4", SqlDialects.from(DatabaseType.MYSQL).createTableSuffix());
        assertEquals(" ENGINE=InnoDB DEFAULT CHARSET=utf8mb4", SqlDialects.from(DatabaseType.MARIADB).createTableSuffix());
        assertEquals("", SqlDialects.from(DatabaseType.SQLITE).createTableSuffix());
        assertEquals("", SqlDialects.from(DatabaseType.POSTGRESQL).createTableSuffix());
    }

    @Test
    public void testColumnTypesAndAutoIncrementKeywords() {
        ColumnDefinition integerAutoIncrement = new ColumnDefinition("id", "INT").setAutoIncrement(true).setPrimaryKey(true);
        ColumnDefinition decimal = new ColumnDefinition("amount", "DECIMAL").setLength(10).setDecimal(2);
        ColumnDefinition enumColumn = new ColumnDefinition("state", "ENUM").setEnumValues("OPEN", "CLOSED");

        assertEquals("AUTO_INCREMENT", SqlDialects.from(DatabaseType.MYSQL).autoIncrementKeyword(integerAutoIncrement));
        assertEquals("AUTO_INCREMENT", SqlDialects.from(DatabaseType.MARIADB).autoIncrementKeyword(integerAutoIncrement));
        assertEquals("", SqlDialects.from(DatabaseType.SQLITE).autoIncrementKeyword(integerAutoIncrement));
        assertEquals("GENERATED BY DEFAULT AS IDENTITY", SqlDialects.from(DatabaseType.POSTGRESQL).autoIncrementKeyword(integerAutoIncrement));

        assertEquals("DECIMAL(10,2)", SqlDialects.from(DatabaseType.MYSQL).columnType(decimal));
        assertEquals("ENUM('OPEN', 'CLOSED')", SqlDialects.from(DatabaseType.MYSQL).enumColumnType(enumColumn));
        assertEquals("TEXT", SqlDialects.from(DatabaseType.SQLITE).enumColumnType(enumColumn));
        assertEquals("TEXT", SqlDialects.from(DatabaseType.POSTGRESQL).enumColumnType(enumColumn));
        assertEquals("INTEGER", SqlDialects.from(DatabaseType.SQLITE).columnType(integerAutoIncrement));
    }

    @Test
    public void testUpdatedAtDefaults() {
        assertEquals("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP", SqlDialects.from(DatabaseType.MYSQL).updatedAtDefaultValue());
        assertEquals("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP", SqlDialects.from(DatabaseType.MARIADB).updatedAtDefaultValue());
        assertEquals("CURRENT_TIMESTAMP", SqlDialects.from(DatabaseType.SQLITE).updatedAtDefaultValue());
        assertEquals("CURRENT_TIMESTAMP", SqlDialects.from(DatabaseType.POSTGRESQL).updatedAtDefaultValue());
    }

    @Test
    public void testUpsertStrategies() {
        Schema schema = SchemaBuilder.upsert("users", table -> {
            table.autoIncrementBigInt("id");
            table.string("username", "sarah").unique();
            table.string("email", "sarah@example.com");
        });

        assertEquals(" ON DUPLICATE KEY UPDATE ", SqlDialects.from(DatabaseType.MYSQL).upsertConflictClause(schema));
        assertEquals(" ON DUPLICATE KEY UPDATE ", SqlDialects.from(DatabaseType.MARIADB).upsertConflictClause(schema));
        assertEquals(" ON CONFLICT (`username`) DO UPDATE SET ", SqlDialects.from(DatabaseType.SQLITE).upsertConflictClause(schema));
        assertEquals(" ON CONFLICT (\"username\") DO UPDATE SET ", SqlDialects.from(DatabaseType.POSTGRESQL).upsertConflictClause(schema));

        assertEquals("`email` = ?", SqlDialects.from(DatabaseType.MYSQL).upsertUpdateExpression("`email`", false));
        assertEquals("`email` = VALUES(`email`)", SqlDialects.from(DatabaseType.MYSQL).upsertUpdateExpression("`email`", true));
        assertEquals("\"email\" = excluded.\"email\"", SqlDialects.from(DatabaseType.POSTGRESQL).upsertUpdateExpression("\"email\"", false));

        assertTrue(SqlDialects.from(DatabaseType.MYSQL).usesUpsertUpdateParameters(false));
        assertFalse(SqlDialects.from(DatabaseType.MYSQL).usesUpsertUpdateParameters(true));
        assertFalse(SqlDialects.from(DatabaseType.POSTGRESQL).usesUpsertUpdateParameters(false));
        assertFalse(SqlDialects.from(DatabaseType.SQLITE).usesUpsertUpdateParameters(true));
    }
}
