package fr.maxlego08.sarah;

import fr.maxlego08.sarah.conditions.ColumnDefinition;
import fr.maxlego08.sarah.database.DatabaseType;
import fr.maxlego08.sarah.database.Schema;
import fr.maxlego08.sarah.dialect.SqlDialect;
import fr.maxlego08.sarah.dialect.SqlDialects;
import fr.maxlego08.sarah.logger.Logger;
import fr.maxlego08.sarah.requests.CreateRequest;
import org.junit.jupiter.api.Test;

import java.lang.reflect.InvocationHandler;
import java.lang.reflect.Method;
import java.lang.reflect.Proxy;
import java.sql.Connection;
import java.sql.PreparedStatement;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class PostgreSqlCreateRequestTest {

    private final SqlDialect postgres = SqlDialects.from(DatabaseType.POSTGRESQL);
    private final DatabaseConfiguration config = new DatabaseConfiguration("", "u", "p", 5432, "localhost", "db", false, DatabaseType.POSTGRESQL);

    @Test
    public void testPostgreSqlAutoIncrementBigIntColumn() {
        ColumnDefinition column = new ColumnDefinition("id", "BIGINT").setAutoIncrement(true);
        column.setPrimaryKey(true);

        assertEquals("\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL", column.build(config, postgres));
    }

    @Test
    public void testPostgreSqlEnumFallsBackToText() {
        ColumnDefinition column = new ColumnDefinition("status", "ENUM").setEnumValues("OPEN", "CLOSED");
        assertEquals("\"status\" TEXT NOT NULL", column.build(config, postgres));
    }

    @Test
    public void testPostgreSqlCreateRequestRendersWithDialect() throws Exception {
        final Recording recording = new Recording();

        DatabaseConnection connection = new DatabaseConnection(config, new NoopLogger()) {
            @Override
            public Connection connectToDatabase() {
                return createConnectionProxy(recording);
            }
        };

        Schema schema = SchemaBuilder.create(null, "users", table -> {
            table.autoIncrementBigInt("id");
            table.string("username", 50).unique();
            table.bigInt("group_id");
            table.foreignKey("groups", "id", true);
        });

        new CreateRequest(schema).execute(connection, config, new NoopLogger());

        assertTrue(recording.query.startsWith("CREATE TABLE IF NOT EXISTS \"users\""));
        assertTrue(recording.query.contains("\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL"));
        assertTrue(recording.query.contains("PRIMARY KEY (\"id\")"));
        assertTrue(recording.query.contains("FOREIGN KEY (\"group_id\") REFERENCES \"groups\"(\"id\") ON DELETE CASCADE"));
        assertTrue(recording.query.endsWith(")"));
    }

    @Test
    public void testPostgreSqlCreateTableHasNoMysqlSuffix() {
        assertEquals("", postgres.createTableSuffix());
    }

    @Test
    public void testMysqlCreateTableSuffixStaysStable() {
        assertEquals(" ENGINE=InnoDB DEFAULT CHARSET=utf8mb4", SqlDialects.from(DatabaseType.MYSQL).createTableSuffix());
    }

    private static Connection createConnectionProxy(final Recording recording) {
        InvocationHandler handler = new InvocationHandler() {
            @Override
            public Object invoke(Object proxy, Method method, Object[] args) {
                String methodName = method.getName();
                if ("prepareStatement".equals(methodName)) {
                    recording.query = (String) args[0];
                    return createPreparedStatementProxy();
                }
                if ("isClosed".equals(methodName)) {
                    return false;
                }
                if ("isValid".equals(methodName)) {
                    return true;
                }
                return defaultValue(method.getReturnType());
            }
        };
        return (Connection) Proxy.newProxyInstance(Connection.class.getClassLoader(), new Class[]{Connection.class}, handler);
    }

    private static PreparedStatement createPreparedStatementProxy() {
        InvocationHandler handler = new InvocationHandler() {
            @Override
            public Object invoke(Object proxy, Method method, Object[] args) {
                String methodName = method.getName();
                if ("execute".equals(methodName)) {
                    return true;
                }
                if ("getUpdateCount".equals(methodName)) {
                    return 0;
                }
                return defaultValue(method.getReturnType());
            }
        };
        return (PreparedStatement) Proxy.newProxyInstance(PreparedStatement.class.getClassLoader(), new Class[]{PreparedStatement.class}, handler);
    }

    private static Object defaultValue(Class<?> returnType) {
        if (returnType == Boolean.TYPE) {
            return false;
        }
        if (returnType == Integer.TYPE) {
            return 0;
        }
        if (returnType == Long.TYPE) {
            return 0L;
        }
        return null;
    }

    private static class Recording {
        private String query;
    }

    private static class NoopLogger implements Logger {
        @Override
        public void info(String string) {
        }
    }
}
